spring:
  application:
    name: bizsimulator

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5437/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  web:
    resources:
      static-locations: classpath:/resources/, classpath:/static/
token:
  jwt:
    secret: ${TOKEN_JWT_SECRET:"jbQxmExX43va4BhnHLcPvnJwQAZAVKWp"}
    expiration: ${TOKEN_EXPIRATION:86400000}

server:
  port: 8081

bizsimulator:
  business:
    coffee-shop:
      start-stock: 300
      start-staff: 1.0
      start-cost: 45
      base-demand: 75
      avg-price: 175
      elasticity: 1.2
      marketing-efficiency: 0.10
      fixed-cost: 4000
      salary-per-staff: 3000
      event-probability: 0.2