spring:
  application:
    name: bizsimulator

  datasource:
    url: jdbc:postgresql://localhost:5437/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  web:
    resources:
      static-locations: classpath:/resources/, classpath:/static/
token:
  jwt:
    secret: "jbQxmExX43va4BhnHLcPvnJwQAZAVKWp"
    expiration: 86400000

server:
  port: 8081